blog/urls.py
from django.urls import path
from blog.views import craete_blog_view,edit_blog_view,contact,PostDetailView



app_name = 'blog'

urlpatterns = [
    path("craete/" , craete_blog_view,name="craete"),
    path('<slug>/',PostDetailView.as_view(),name='detail'),

    path('<slug>/edit',edit_blog_view,name="edit"),
    path('contact',contact,name='contact'),





]

trblog/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from account.views import home_view,must_auth,home_screen_view

from blog import views

from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view,name='home'),

    path('account/', include('account.urls', 'account')),

    path('blog/', include('blog.urls', 'blog')),
    path('must_auth/',must_auth, name="must_auth"),


    #path('activate/<slug:uidb64>/<slug:token>/',views.activate1,name='activate'),

    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),


]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone
from cloudinary.models import CloudinaryField


CAEGORY_CHOICES = (
    ('Sweets','Sweets'),
    ('Healthy','Healthy'),
    ('Pastry','Pastry'),
   
)

def upload_location(instance, filename):
	file_path = 'trblog/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=5000, null=False, blank=False)
	image = 				models.ImageField(blank=True,default='images_4.jpeg')
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)
	category = models.CharField(choices=CAEGORY_CHOICES, max_length=7)



	def __str__(self):
		return self.title

	@property
	def number_of_comments(self):
		return Comment.objects.filter(post_connected=self).count()

	@property
	def image_url(self):
		if self.image and hasattr(self.image, 'url'):
			return self.image.url



class Comment(models.Model):
    cotent = models.TextField(max_length=140)
    data_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post_connected = models.ForeignKey(BlogPost,on_delete=models.CASCADE)  


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms
from blog.models import BlogPost

from .models import Comment

class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['cotent'] 




class createBlogePostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']


class UPdateBlogPost(forms.ModelForm):
    class Meta :
        model = BlogPost
        fields = ['title' , 'body' , 'image']

    def save(self,commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']
        if commit:
            blog_post.save()
        return blog_post

blog/views.py
from django.shortcuts import render ,redirect ,get_list_or_404, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from blog.models import BlogPost ,Comment
from account.models import Account
from blog.forms import createBlogePostForm,UPdateBlogPost,NewCommentForm
from django.views.generic import DetailView
from django.core.mail import send_mail





def craete_blog_view(request):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_auth')

    form = createBlogePostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = createBlogePostForm()
    context['form'] = form
    return render(request , 'blog/create_blog.html')





class PostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/detail_blog.html'
    context_object_name = 'blog_post'
 

    def get_context_data(self,**kwargs):
        data = super().get_context_data(**kwargs)
        comments_connected = Comment.objects.filter(post_connected=self.get_object()).order_by('data_posted')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['form'] = NewCommentForm(instance=self.request.user) 
        return data
    
    def post(self, request, *args,**kwargs):
        new_comment = Comment(cotent=request.POST.get('cotent'), author=self.request.user, post_connected=self.get_object() )
        new_comment.save()

        return self.get(self , request,*args,**kwargs)



def edit_blog_view(request,slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_auth')

    blog_post =get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse('ha your not author of this post ')
    if request.POST:
        form = UPdateBlogPost(request.POST or None , request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj=form.save()
            context['success_messeage'] = "It Updated"
            blog_post=obj
    form=UPdateBlogPost(
        initial={
            "title": blog_post.title,
			"body": blog_post.body,
			"image": blog_post.image,

        }
    )
    context['form'] = form
    return render(request, 'blog/edit_blog.html', context )



def contact(request):

    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        

        send_mail(
            message_name,
            message,
            message_email,
            ['fatimhalbshir@gmail.com'],


        )
        return render(request,'contact.html',{'message_name':message_name})

    else:
        return render(request,'blog/contact.html',{})

blog/templates/blog/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="styeel page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="styeel page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class=" page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class=" page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

blog/templates/blog/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>
{% load cloudinary %}

{% if blog_post %}

<section>
    <div class="single-post-item">
        <figure>
                <img class="card-img-top post-img img-fluid"  src=" {{ post.image_url|default_if_none:'#' }} " >
        </figure>
        <h3>
           
            <a href="{% url 'blog:detail' post.slug %}">{{post.title}}</a>
        </h3>
         <p >{{post.body|safe|truncatechars:180}}</p>
         {% if post.author == request.user %}
			  	<a href="{% url 'blog:edit' post.slug %}" class="btn btn-primary">Update</a>
		{% endif %}

        
        <a href="{% url 'blog:detail' post.slug %}" class="primary-btn text-uppercase mt-15">continue Reading</a>
        <div class="post-box">
            <div class="d-flex">
                <div >
                   
                        <img src="{{post.author.image.url}}" style="width: 80px; height: 80px;" class="rounded-circle" alt="">
                   
                </div>
                
                <div class="post-meta">
                    <div class="meta-head">
                        <a href="#">{{post.author.username}}</a>
                    </div>
                    <div class="meta-details">
                        <ul>
                            
                            <li>
                                <a href="#">
                                    <span class="lnr lnr-calendar-full"></span>
                                    Updated on {{post.date_updated}}
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="lnr lnr-tag"></span>
                                    {{post.category}}
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="lnr lnr-bubble"></span>
                                    {{post.number_of_comments}}

                                </a>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% else %}

<div class="container">
    <div class="row">
        <div class="card m-auto">
            <div class="card-body mt-2 mb-2">
                <h2 class="card-title">No results</h2>
                <p class="card-text"> No result matchin your search : "{{query}}"</p>

            </div>
        </div>
    </div> 

</div>



{% endif %}

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% block content %}

		<!-- start banner Area -->
	<section class="banner-area relative">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">
						Contact Us
					</h1>
					<p class="text-white link-nav"><a href="/">Home </a> <span class="lnr lnr-arrow-right"></span> <a href="">
							Contact Us</a></p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->
 
	{% if message_name %}
	<div class="card" style="text-align: center;">
	  <h2>thank  - {{ message_name }}</h2> 
	 <p>we recive email will rspond shrtly.....</p>
	 <br/><br/><br/><br/>
   </div>
  
	{% else %}
	
	<!-- Start contact-page Area -->
	<section class="contact-page-area section-gap">
		<div class="container">
			<div class="row">
				<div class="map-wrap"  id="map"></div>
				<div class="col-lg-4 d-flex flex-column address-wrap">
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-home"></span>
						</div>
						<div class="contact-details">
							<h5>Omdorman, sudan</h5>
							<p>56/8, West </p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-phone-handset"></span>
						</div>
						<div class="contact-details">
							<h5>00 (249) 9865 562</h5>
							<p>Mon to Fri 9am to 6 pm</p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-envelope"></span>
						</div>
						<div class="contact-details">
							<h5>myemail@gmail.com</h5>
							<p>Send us your query anytime!</p>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<form action="{% url 'blog:contact'  %}" method="post">{% csrf_token %}
						<div class="row">
						  <div class="col-lg-6">
							<input type="text" name="message-name" class="form-control mb-30" placeholder="Your Name">
						  </div>
						  <div class="col-lg-6">
							<input type="email" name="message-email" class="form-control mb-30" placeholder="Your Email">
						  </div>
						  <div class="col-12">
							<textarea name="message" class="form-control mb-30" placeholder="Your Message"></textarea>
						  </div>
						  <div class="col-12">
							<button type="submit" class="btn dento-btn">Send Message</button>
						  </div>
						</div>
					  </form>
				</div>
			</div>
		</div>
	</section>
	{% endif %}
	
	{% endblock content %}

blog/templates/blog/create_blog.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
    <div><br /><br /><br /><br></div>
    
    <div class="row">
        <div class="card col-lg-7 offset-lg-2">
            <div class="card-header">
        
        <h3 class="">Creat Recipe</h3>
    </div>
        
        <div class="card-body ">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                
                <div class="form-group mt-10">
                    <input  class="form_control single-input" type="text" name="title" id="id_title" placeholder="Tilte" required autofocus>
                    
                </div>
                
                <div class="form-group mt-10">
                    <label for="id_body">Content</label>
                    <textarea class="from-control single-input" rows="10" type="text"  name="body" id="id_body" placeholder="Blog is about...." required></textarea>

                </div>
                <div class="form-group">
                    <label for="id_image">Image</label>
                    <input type="file" name="image" id="id_image" accept="image/*" required>

                </div>

				
                <button class="submit-buttom btn btn=lg btn=primary btn-block" type="submit">Creat Post</button>


            </form> 

        </div>
    </div>

    </div>

</div>  

               

{% endblock content %}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}


<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<section class="banner-area relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Blog Details
				</h1>
				<p class="text-white link-nav"><a href="/">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="#">
						Blog Details</a></p>
			</div>
		</div>
	</div>
</section>

<section class="blog_area section-gap single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="main_blog_details">
					<img class="card-img-top img-fluid" src="{{blog_post.image.url}}" alt="">
					<h4>{{blog_post.title}}</h4>
					<div class="user_details">
						
						<div class="float-right">
							<div class="media">
								<div class="media-body">
									<h5>{{blog_post.author.username}}</h5>
									<p>{{blog_post.date_updated}} </p>
								</div>
								<div class="d-flex">
									<img src="{{blog_post.author.image.url}}" class="rounded-circle" alt="">
								</div>
							</div>
						</div>
					</div>
					<p>{{blog_post.body|safe}}</p>
					

					{% if blog_post.author == request.user %}
			  	<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
			  {% endif %}
					
					
					<div class="news_d_footer">
						<a class="justify-content-center ml-auto" href="#"
						><i class="lnr lnr lnr-bubble"></i>{{ blog_post.number_of_comments }} Comments</a>
						
					</div>
				</div>
				
				<div class="comments-area">
					<h4>{{ blog_post.number_of_comments }} Comments</h4>
					<div class="comment-list">
						{% for comment in comments %}
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="img/blog/c1.jpg" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{ comment.author.username }}</a></h5>
									<p class="date">{{ comment.data_posted | date:"H:i l, d.m.y" }} </p>
									<p class="comment">
										{{ comment.cotent }}
									</p>
								</div>
							</div>
							
						</div>
						{% endfor %}
					</div>
					
				</div>
				<div class="comment-form">
					<h4>Leave a Reply</h4>
					{% if user is not None %}
					<form method="POST">
						{% csrf_token %}
						<div class="form-group">
                        <fieldset class="form-group"  >
                            {{ form | crispy }}
						</fieldset>
					</div>
                        <div class="form-group">
                            <button class="btn btn-outline-primary" type="submit">Submit comment</button>
                        </div>
					</form>
					{% endif %}
				</div>
			</div>


			<div class="right-column col-lg-3 d-lg-flex  flex-column">
				<div class="single-widget search-widget">
					<form method="get" class="example" action="#" style="margin:auto;max-width:300px">
						<input type="text" placeholder="Search Posts" name="q" id="id_q">
						<button type="submit"><i class="fa fa-search"></i></button>
					</form>
				</div>
				</div>
				</div>
				





			</div>
			</div>
			</section>
			

			<script type="text/javascript">
				document.getElementById("id_q").value = "{{query}}"
			</script>
			
	

{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>
<br><br><br><br>
<div class="container">
	<div class="row " >
		

		<div class="col-lg-7 offset-lg-1" >

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
			<div class="card">
				<div class="card-header"><h1>Update Your Post</h1> </div>
				<div class="card-body">
					<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

						<!-- title -->
						<div class="form-group">
							<label for="id_title">Title</label>
							<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
						</div>
		
						<!-- Body -->
						<div class="form-group">
							<label for="id_body">Content</label>
							<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
							required>{{form.initial.body}}</textarea>
						</div>
		
						<!-- Image -->
						<div class="form-group image-group" id="id_image_group">
							<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
							  <div class="middle">
								<div class="text">Change image</div>
							  </div>
						</div>
						<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
						
		
						{% for field in form %}
							<p>
								{% for error in field.errors %}
									<p style="color: red">{{ error }}</p>
								{% endfor %}
							</p>
						{% endfor %}
						{% if form.non_field_errors %}
							<div style="color: red">
								<p>{{form.non_field_errors}}</p>
							</div>
						{% endif %}
		
						<!-- Submit btn -->
						<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
					</form>
				</div>
			</div>
				
		</div>
	</div>
</div>

<script type="text/javascript">
    document.getElementById('id_image_group').onclick = function(event){
        document.getElementById('id_image_file').click();
    };

    function readURL(input){
        var reader = new FileReader();
        reader.onload = function(e){
            $('#id_image_display')
            .attr('new' ,e.target.result)
        };
        reader.readAsDataURL(input.files[0])
    }

</script>


{% endblock content %}