account/urls.py
from account import views
from django.conf.urls import url
from django.urls import path


app_name = 'account'


urlpatterns = [
    #path('',views.home_view,name='home'),



    path('signup/',views.usersingup,name='register_user'),
    path('login/',views.Login_view,name='Login'),
    path('logout/',views.logout_view, name="logout"),
    path('account/',views.account_view, name="accountt"),









]

blog/urls.py
from django.urls import path
from blog.views import craete_blog_view,edit_blog_view,contact,PostDetailView



app_name = 'blog'

urlpatterns = [
    path("craete/" , craete_blog_view,name="craete"),
    path('<slug>/',PostDetailView.as_view(),name='detail'),

    path('<slug>/edit',edit_blog_view,name="edit"),
    path('contact',contact,name='contact'),





]

trblog/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from account.views import home_view,must_auth,home_screen_view

from blog import views

from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view,name='home'),

    path('account/', include('account.urls', 'account')),

    path('blog/', include('blog.urls', 'blog')),
    path('must_auth/',must_auth, name="must_auth"),


    #path('activate/<slug:uidb64>/<slug:token>/',views.activate1,name='activate'),

    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),


]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
	{% load static %}

	<title >Sweets&Cake</title>
	<meta name='viewport' content="width=device-width, initial-scale=1.0"> 
	<link rel="stylesheet" type="text/css" href="{% static 'sblog/css/bootstrap.css'%}" />
	<link rel="stylesheet" type="text/css" href="{% static 'sblog/css/style.css'%}" />

        

	<script src="{% static 'sblog/js/bootstrap.js'%}"></script>


	<link rel="stylesheet" href="{% static 'sblog/css/linearicons.css' %} ">
	<link rel="stylesheet" href="{% static 'sblog/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'sblog/css/bootstrap.css' %} ">
	<link rel="stylesheet" href="{% static 'sblog/css/magnific-popup.css' %} ">
	<link rel="stylesheet" href="{% static 'sblog/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'sblog/css/animate.min.css' %} ">
	<link rel="stylesheet" href="{% static 'sblog/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'sblog/css/main.css' %} ">
	{% include 'header.html' %}
</head>

<body>

<!-- Body -->
<style type="text/css">
	.main{
		min-height: 100vh;
		height: 100%;
	}
</style>
<div class="main ">
	

	{% block content %}

	{% endblock content %}
	

</div>
<!-- End Body -->

	<script src="{% static 'sblog/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="{% static 'sblog/js/vendor/bootstrap.min.js' %} "></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="{% static 'sblog/js/easing.min.js' %}"></script>
	<script src="{% static 'sblog/js/hoverIntent.js' %}"></script>
	<script src="{% static 'sblog/js/superfish.min.js' %} "></script>
	<script src="{% static 'sblog/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'sblog/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'sblog/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'sblog/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'sblog/js/waypoints.min.js' %}"></script>
	<script src="{% static 'sblog/js/mail-script.js' %} "></script>
	<script src="{% static 'sblog/js/main.js' %}"></script>
</body>
{% include 'footer.html' %}

</html>

templates/footer.html
<style type="text/css">
	.footer{
		min-height: 50px;
		width: 100% !important;

	}
	.styeel{
		width: 100% !important;
	}
</style>

<!-- Footer -->
<br>



<footer class="footer-area page-footer text-center font-small mt-4 wow fadeIn " >

	<hr class="my-4">

	<!-- Social icons -->
	<div class="pb-1 st"style="color: blueviolet !important;" >
	  <a href="" target="_blank">
		<i class="fa fa-facebook-f mr-3"></i>
	  </a>

	  <a href="" target="_blank">
		<i class="fa fa-twitter mr-3"></i>
	  </a>

	 
	  <a href="" target="_blank">
		<i class="fa fa-pinterest mr-3"></i>
	  </a>

	  
	</div>
	<!-- Social icons -->

	<!--Copyright-->
	<div class="footer-copyright py-1">
	  © 2021 Copyright:
	  <a href="" target="_blank"> Food Bolg </a>
	</div>
	<!--/.Copyright-->

  </footer>

templates/header.html
<style type="text/css">
	@media (min-width: 768px) {
	  html {
	    font-size: 16px;
	  }
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}
	form{
		width: 100%;
	}
</style>

<header id="header" >
    <div class="container box_1170 main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="/">
                    {% if request.user.is_authenticated %}
                    <h3 class=" p-2 text-light" style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; color: deeppink !important ;"> Hellow {{request.user.username}}"</h3>
                {% endif %}
                </a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="/">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'account:accountt' %}">Account</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'account:Login' %}">Login</a></li>
                    <li><a href="{% url 'account:register_user' %}">Register</a></li>

                    {% endif %}
                    
                    <li><a href="{% url 'blog:contact' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>